version: '3.1'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 5000:80
    networks:
      - my-network
    depends_on:
      - db
  db:
    hostname: db
    build:
      context: ./Database
      dockerfile: Dockerfile
    # ports:
    #   - 1433:1433
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
  