# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY WebShopShoes/*.csproj ./WebShopShoes/
RUN dotnet restore

# copy everything else and build app
COPY WebShopShoes/. ./WebShopShoes/
WORKDIR /source/WebShopShoes
RUN dotnet build -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /source
COPY --from=build /source ./
CMD ["ls -l"]
